// @vitest-environment jsdom
import { describe, expect, it } from 'vitest';
import type { RenderedReceipt } from '@brb/shared';
import {
  ALLOWED_SVG_TAGS,
  CAUTION_CONFIDENCE,
  previewFacts,
  printerChoices,
  sanitiseSvg,
} from './view.ts';

function rendered(overrides: Partial<RenderedReceipt> = {}): RenderedReceipt {
  return {
    format: 'svg',
    content: '<svg/>',
    ticketNumber: '1167',
    confidence: 1,
    warnings: [],
    columns: 42,
    byteCount: 856,
    ...overrides,
  };
}

describe('previewFacts', () => {
  it('names the ticket and the grid it is laid out on', () => {
    const facts = previewFacts(rendered());
    expect(facts.title).toBe('Ticket n° 1167');
    expect(facts.ticket).toBe('n° 1167');
    expect(facts.confidence).toBe('100 %');
    expect(facts.width).toBe('42 colonnes');
    expect(facts.warnings).toBe('');
  });

  it('prefers a label from the source when there is one', () => {
    expect(previewFacts(rendered(), 'recu-1167.pdf').title).toBe('recu-1167.pdf');
  });

  it('warns when the reading was uncertain', () => {
    const facts = previewFacts(rendered({ confidence: 0.6 }));
    expect(facts.warnings).toContain('60 %');
    expect(facts.warnings).toContain('vérifiez les montants');
  });

  it('lists the parser warnings verbatim', () => {
    const facts = previewFacts(
      rendered({ warnings: [{ code: 'ITEMS_SUM_MISMATCH', message: 'La somme diffère.' }] }),
    );
    expect(facts.warnings).toContain('La somme diffère.');
  });

  it('says which characters will not print as written', () => {
    const facts = previewFacts(rendered({ unmapped: ['’', 'œ'] }));
    expect(facts.warnings).toContain('’ œ');
    expect(facts.warnings).toContain('remplacés');
  });

  it('lets the user print regardless of confidence', () => {
    // Someone looking at the ticket is a better judge than a threshold; the
    // threshold is what gates automatic printing.
    expect(previewFacts(rendered({ confidence: 0.2 })).canPrint).toBe(true);
    expect(CAUTION_CONFIDENCE).toBe(0.9);
  });

  it('counts no bytes, since the two printers are sent different jobs', () => {
    // A thermal printer gets the ESC/POS; an ordinary one gets a rendered PDF
    // of a quite different size. A number right for one and wrong for the
    // other is worse than none.
    const facts = previewFacts(rendered({ byteCount: 856 }));
    expect(facts.width).toBe('42 colonnes');
    expect(JSON.stringify(facts)).not.toContain('octets');
  });
});

describe('sanitiseSvg', () => {
  function parse(markup: string): Element {
    return new DOMParser().parseFromString(markup, 'image/svg+xml').documentElement;
  }

  it('keeps the shapes the decoder emits', () => {
    const svg = parse(
      '<svg xmlns="http://www.w3.org/2000/svg"><rect/><g><text>Ticket</text></g><line/></svg>',
    );
    sanitiseSvg(svg);
    expect(svg.querySelector('rect')).not.toBeNull();
    expect(svg.querySelector('text')?.textContent).toBe('Ticket');
    expect(svg.querySelector('line')).not.toBeNull();
  });

  it('removes a script, which would run once the SVG is inserted', () => {
    // The markup is generated by this project, but it arrives as a string and
    // ends up in a live document, so it is treated as untrusted.
    const svg = parse(
      '<svg xmlns="http://www.w3.org/2000/svg"><script>globalThis.pwned = 1</script><text>x</text></svg>',
    );
    sanitiseSvg(svg);
    expect(svg.querySelector('script')).toBeNull();
    expect(svg.querySelector('text')).not.toBeNull();
  });

  it('removes anything outside the allowed set', () => {
    const svg = parse(
      '<svg xmlns="http://www.w3.org/2000/svg"><foreignObject/><image/><use/><text>x</text></svg>',
    );
    sanitiseSvg(svg);
    for (const tag of ['foreignObject', 'image', 'use']) {
      expect(svg.querySelector(tag), tag).toBeNull();
    }
    expect(ALLOWED_SVG_TAGS.has('text')).toBe(true);
  });

  it('strips event handler attributes', () => {
    const svg = parse(
      '<svg xmlns="http://www.w3.org/2000/svg"><text onload="globalThis.pwned = 1" onclick="x()">y</text></svg>',
    );
    sanitiseSvg(svg);
    const text = svg.querySelector('text');
    expect(text?.hasAttribute('onload')).toBe(false);
    expect(text?.hasAttribute('onclick')).toBe(false);
  });

  it('leaves the drawing attributes alone', () => {
    const svg = parse(
      '<svg xmlns="http://www.w3.org/2000/svg"><text x="12" y="20" font-size="13">y</text></svg>',
    );
    sanitiseSvg(svg);
    expect(svg.querySelector('text')?.getAttribute('font-size')).toBe('13');
  });
});

describe('printerChoices', () => {
  const PRINTERS = [{ name: 'EPSON TM-T88V' }, { name: 'HP LaserJet' }];

  it('offers every queue the host can see, not just thermal ones', () => {
    // The user picks; the extension does not decide which printer is suitable.
    const choices = printerChoices(PRINTERS, 'EPSON TM-T88V', 'windows');
    expect(choices.options.map((option) => option.value)).toEqual([
      'EPSON TM-T88V',
      'HP LaserJet',
    ]);
  });

  it('starts on the configured printer, so the common case is one click', () => {
    const choices = printerChoices(PRINTERS, 'HP LaserJet', 'windows');
    expect(choices.selected).toBe('HP LaserJet');
    expect(choices.note).toBe('');
  });

  it('offers a configured printer the driver cannot see', () => {
    // That is what a direct port looks like - COM3, 192.168.1.50:9100 - and no
    // driver lists it. Without this it could never be chosen here, which on
    // the till where this was found was the only printer that worked.
    const choices = printerChoices(PRINTERS, 'COM3', 'windows');
    expect(choices.selected).toBe('COM3');
    expect(choices.options.map((option) => option.value)).toContain('COM3');
  });

  it('selects nothing when no printer is configured at all', () => {
    const choices = printerChoices(PRINTERS, '', 'windows');
    expect(choices.selected).toBe('');
    expect(choices.note).toContain('Choisissez');
  });

  it('says so when the list comes from a mock driver', () => {
    const choices = printerChoices(PRINTERS, 'EPSON TM-T88V', 'mock');
    expect(choices.note).toContain('mock');
    expect(choices.selected).toBe('EPSON TM-T88V');
  });

  it('does not call the machine’s real queues fake', () => {
    // The CUPS driver lists the printers this computer actually has; warning
    // about them the way the mock driver is warned about would be the lie the
    // note exists to prevent.
    const choices = printerChoices(PRINTERS, 'HP LaserJet', 'cups');
    expect(choices.note).toBe('');
    expect(choices.selected).toBe('HP LaserJet');
  });

  it('says so when the poste has no printer at all', () => {
    const choices = printerChoices([], 'EPSON TM-T88V', 'windows');
    expect(choices.options).toEqual([]);
    expect(choices.note).toContain('Aucune imprimante');
  });
});
