import type { RenderedReceipt } from '@brb/shared';

/**
 * What the approval page shows.
 *
 * Pure, like the popup's and the options page's view models, so the wording and
 * every threshold are testable without a DOM.
 */

/** Below this, the page says to look before approving. */
export const CAUTION_CONFIDENCE = 0.9;

export interface PreviewFacts {
  title: string;
  ticket: string;
  confidence: string;
  /** Size of the job that will be sent. */
  size: string;
  /** Anything worth reading before approving; empty when there is nothing. */
  warnings: string;
  canPrint: boolean;
}

export function previewFacts(rendered: RenderedReceipt, label?: string): PreviewFacts {
  const percent = Math.round(rendered.confidence * 100);
  const notes: string[] = [];

  if (rendered.confidence < CAUTION_CONFIDENCE) {
    notes.push(`Lecture incertaine (${percent} %) : vérifiez les montants ci-contre.`);
  }
  for (const warning of rendered.warnings) notes.push(warning.message);
  if (rendered.unmapped !== undefined && rendered.unmapped.length > 0) {
    // Worth saying: these characters will not appear as written on the paper.
    notes.push(`Caractères remplacés à l’impression : ${rendered.unmapped.join(' ')}`);
  }

  return {
    title: label ?? `Ticket n° ${rendered.ticketNumber}`,
    ticket: `n° ${rendered.ticketNumber}`,
    confidence: `${percent} %`,
    size:
      rendered.byteCount === undefined
        ? `${rendered.columns} colonnes`
        : `${rendered.byteCount} octets, ${rendered.columns} colonnes`,
    warnings: notes.join('\n'),
    // Printable whatever the confidence: a person looking at the ticket is a
    // better judge than a threshold. The threshold gates automatic printing.
    canPrint: true,
  };
}

/**
 * The printer list, and which entry starts selected.
 *
 * Every queue the host can see is offered - the choice is made here, per job,
 * and never written back to the settings. The configured printer starts
 * selected so the common case is one click; when there is none, or it has gone
 * missing, nothing is preselected and the page says to choose.
 */
/**
 * Drivers whose queues are not real hardware.
 *
 * Named rather than inferred from "anything but windows": the CUPS driver lists
 * the machine's actual printers, and calling those fake would be the lie this
 * warning exists to prevent.
 */
export const PRETEND_ADAPTERS = ['mock', 'file'];

export interface PrinterChoices {
  options: { value: string; label: string }[];
  selected: string;
  /** Empty when a printer is selected; otherwise what the page should say. */
  note: string;
}

export function printerChoices(
  printers: readonly { name: string }[],
  configured: string | undefined,
  adapter?: string,
): PrinterChoices {
  const known = printers.some((printer) => printer.name === configured);
  const options = printers.map((printer) => ({ value: printer.name, label: printer.name }));

  if (printers.length === 0) {
    return { options, selected: '', note: 'Aucune imprimante détectée sur ce poste.' };
  }
  if (adapter !== undefined && PRETEND_ADAPTERS.includes(adapter)) {
    return {
      options,
      selected: known && configured !== undefined ? configured : '',
      note: `Liste fournie par le pilote « ${adapter} » : ce ne sont pas de vraies imprimantes.`,
    };
  }
  if (!known) {
    // Including the case where the configured printer has been unplugged: a
    // silent fallback to another queue is worse than asking.
    return { options, selected: '', note: 'Choisissez une imprimante.' };
  }
  return { options, selected: configured ?? '', note: '' };
}

/**
 * Keep only the shapes the decoder produces.
 *
 * The SVG is generated by this project from ESC/POS bytes, and the decoder
 * escapes its text - but it arrives as a string and is inserted into a page, so
 * it is treated as untrusted anyway. A `<script>` inside an imported SVG does
 * run once inserted, which is exactly what this removes.
 */
export const ALLOWED_SVG_TAGS = new Set(['svg', 'g', 'rect', 'text', 'line', 'tspan']);

export function sanitiseSvg(root: Element): Element {
  for (const element of [...root.querySelectorAll('*')]) {
    if (!ALLOWED_SVG_TAGS.has(element.tagName.toLowerCase())) {
      element.remove();
      continue;
    }
    for (const attribute of [...element.attributes]) {
      // No event handlers.
      if (attribute.name.toLowerCase().startsWith('on')) element.removeAttribute(attribute.name);
    }
  }
  return root;
}
